// <auto-generated />
namespace DollarApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class adddollar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddollar));
        
        string IMigrationMetadata.Id
        {
            get { return "201506261413380_adddollar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
